### ISSUE TITLE
Will there be an upgrade to Python3?

### ISSUE THREAD

**Issue by krishnachaitanya9** [juliencegarra/OpenMATB#1]
Hey! Thanks for the great software. I am using MATB binaries provided by NASA. But that only works on Windows which is sad. I was looking for a Linux port then I found this one. Will there be Python3 support for this in the near future?

**Comment by juliencegarra** [comment]
Yes it is on the todo list! However you do not need Python3 to use OpenMATB right now on linux. Install Python2 and you will be fine (OpenMATB was tested on both windows and Linux / Debian)

**Comment by juliencegarra** [comment]
We just committed the Python 3 version on the master branch! Let us know if you have any issue
