### ISSUE TITLE
Error in scenario file 

### ISSUE THREAD

**Issue by Sophieforever** [juliencegarra/OpenMATB#10]
Dear Benoit,

I tried to create my own scenario in which participants have to do the tracking task continously and switch to the rest of the tasks from time to time. Nothing should be automated. I would also like to skip the participant info completely.  

When loading my own scenario file, I receive the following error message: 
![image](https://user-images.githubusercontent.com/101716340/164468832-f1542f92-1305-4956-9f46-ce248e040fca.png)

I do not receive this message with the example script provided by you. But I cannot figure out what is the problem with my scenario file! 
Maybe you have an idea on how to solve this issue. 

Thanks a lot!

This is my file: 
[Test_Experiment_1_issue.txt](https://github.com/juliencegarra/OpenMATB/files/8531459/Test_Experiment_1_issue.txt)

**Comment by benoitvalery** [comment]
Hi @Sophieforever.
You have specified execution times where the seconds field exceeds the allowed limit of 60 seconds. See if by converting these lines correctly (for example 0:00:82 becomes 0:01:22), you still get this error.
Best wishes.

**Comment by Sophieforever** [comment]
Ah, that was the problem. Thanks for helping me out!
