### ISSUE TITLE
Suggestions about processing the log-file in MATLAB/R?

### ISSUE THREAD

**Issue by Sophieforever** [juliencegarra/OpenMATB#11]
Dear all, 

I tried to analyse the generated log-file in MATLAB and R. However, I am having a problem to read in the entire dataset. 

For instance, some columns contain different kind of information (numbers/text) and are therefore not loaded properly. 

Do you have by chance any suggestions on how to read the entire log-file in Matlab or R with out data loss?

Best, 
Sophie

**Comment by benoitvalery** [comment]
Hi @Sophieforever ,
Could you post a sample of the log file you want to process and explain more precisely what is the unexpected behavior with this example ?
Best,
Benoît

**Comment by Sophieforever** [comment]
Here is an example file: [Example.log](https://github.com/juliencegarra/OpenMATB/files/9166460/Example.log)

For instance, when trying to read the data in Matlab using the readtable()-function, it looks like that: 
![image](https://user-images.githubusercontent.com/101716340/180409999-a7f88ee1-470c-4fcd-a7bc-25309e13beef.png)

Some of the information is lost or recognized as a Nan, I think because there is mixed data in one column (text and numbers). 

In R I tried to use the read.table() and read_log() functions, but got similar results. Do you know a trick on how to read the file without data loss? Or maybe another program in which one can analyse the log-files?

**Comment by benoitvalery** [comment]
The `readtable` function in Matlab might have an option to handle several formats.
For instance, see if
```
readtable('Example.log','Format','auto')
```
resolve the NaN thing. See the [documentation](https://fr.mathworks.com/help/matlab/ref/readtable.html) of this function for more options. Then you will have to parse the Var7 column by hand depending on what you want to achieve.

Do not hesitate to filter the log file, to retain only the rows you need (for instance the STATE lines).

With these two steps, you might be able to convert the remaining lines into floats, for further processing.

**Comment by benoitvalery** [comment]
Do not hesitate to re-open the ticket if you get into more troubles.
