### ISSUE TITLE
Ask: embedded scenarios 

### ISSUE THREAD

**Issue by thomakl** [juliencegarra/OpenMATB#13]
Hi, 

As I am discovering how to build a scenario, I have caught one detail in the "scenarios\generated\test.txt" file.
It seems that we can call a scenario inside another scenario with 
```
# Custom scenario commands
# Source: Scenarios/custom_incapacitation.txt
```
However, I have adapted it as follows to make it looks like an instruction, but it breaks :
```
# Custom scenario commands
0:00:02;scenarios;filename;scenarios/custom_incapacitation.txt
```

Is there a way to embed scenarios ?

**Comment by benoitvalery** [comment]
Hi @thomakl.
No there is no built-in command to embed a scenario inside another one. For now, only the `scenario_generator.py` is doing such a thing (ll. 285-297). For questions of transparency, it is important that any usable scenario is complete and reviewable (not form with included parts).

**Comment by thomakl** [comment]
Hi @benoitvalery,

I understand. I found an alternative by working with a spreadsheet.
