### ISSUE TITLE
Import module 'Plugins' not found

### ISSUE THREAD

**Issue by thomakl** [juliencegarra/OpenMATB#15]
Hi,

It seems that the directory `OpenMATB/Plugins` should be renamed to `OpenMATB/plugins` to execute properly with the rest of the code.

Cheers

**Comment by benoitvalery** [comment]
Hi @thomakl,
These two typologies are parts of distinct branches, so I am afraid I do not see what you mean. Can you be more precise ?

**Comment by thomakl** [comment]
Hi @benoitvalery ,

You are totally right. The error is coming from my migration from the master branch to the dev branch.
Everything is alright.
