### ISSUE TITLE
Communications plugin with owncallsign not working

### ISSUE THREAD

**Issue by thomakl** [juliencegarra/OpenMATB#19]
Hi,

I would like to set my `owncallsign ` in the Communications plugin with this instruction :
`0:00:00;communications;owncallsign;ENSC23`
or 
`0:00:00;communications;callsignregex;ENSC\d\d`
However, it seems to work and it generates its own call sign anyway.

Cheers

**Comment by benoitvalery** [comment]
Hi @thomakl
I did some test and there are three things to consider :
1. The regex modification does not seem to work currently, I plan to correct it soon (minor bug) ;
2. If you want to set a specific `owncallsign`, the best is to set it *before* you start the task, but I plan to make it more flexible (minor)

```
# 1. Set tasks parameters
# 1.d. Communications parameters
# Change the callsign format, the number of distractive callsigns, the voice gender and idiom
0:00:00;communications;owncallsign;ENSC23

# 2. Start appropriate tasks
0:00:00;communications;start
```
You have to follow the same recommendation for the constant parameters (parameters that do not change throughout the experiment). As the program is gaining flexibility, it becomes more and more possible to change parameters "on the fly". 

3. When (1) will work, a regex mixing fixed letters/number and regular expressions should work too.

I come back soon with a fix.

**Comment by benoitvalery** [comment]
Check the last commit. It should now work. I added a `mwe` folder in the scenario directory so store relevant, minimum working examples.

**Comment by thomakl** [comment]
Hi,
The tip by putting the `owncallsign `before starting the `communications `plugin do the work.
Thank you,
Cheers
