### ISSUE TITLE
Adjust the overall background colour of the interface

### ISSUE THREAD

**Issue by Menglongwinnie** [juliencegarra/OpenMATB#30]
Hello,
Thank you so much for your work. It has been a great help to me. However, I have a problem that I need your help with. 
When I was analysing the fixation data from the MATB task using the eye-tracking device, I found that the fixation mapping was not accurate due to the background colour being too bright. I deduced that this could be solved by darkening the MATB background colour. So I would like to ask if it is possible to adjust the overall background colour of the interface and how to do this. 
I look forward to hearing from you.

**Comment by benoitvalery** [comment]
Hi, it is possible to change to overall color setting of the MATB in the `core/constants.py` file. There, you have a `BACKGROUND` constant that you can set to the desired color (l. 17).

For instance :

```
BACKGROUND=(150, 150, 150, 255)
```
will give you something darker.

Note that you might need to adjust some other colors to get something coherent: for instance, you might have to adjust the `RED` color to contrast it to the darker background. The limit is that, for now, you can only adjust colors, and not the color of each element. For instance, you cannot adjust independently the color of the tracking cursor (`RED`) and the color of a negative feedback (also `RED`). If you want to do that, you will have to dive into the code and find where each element color is set.

Do not hesitate to ask more if you you need

**Comment by Menglongwinnie** [comment]
![1](https://github.com/juliencegarra/OpenMATB/assets/138504487/89b04c78-b123-43a6-8088-387dbedda1fd)
Hello, with your help I have figured out how to change the background colour but haven't managed to implement it yet. 

This is because I was previously working on v1.1, which does not allow me to change the colour in the same way as the current latest version. 

I have installed python 3.9, third-part libraries and created a virtual environment as per the installation prompts for the latest version, but the following problem occurs when executing the new version.

**Comment by benoitvalery** [comment]
There was minor bug in `core/utils.py`, now fixed by the [last commit](https://github.com/juliencegarra/OpenMATB/commit/1aff15a4273874d923ef1ebb04cce157bef221d2). Please check the last master version and see if it works for you.

**Comment by Menglongwinnie** [comment]
Hi, there is another question I need to ask you. 
After connecting the joystick, I have the problem shown in the picture. 
![微信图片_20230711172909](https://github.com/juliencegarra/OpenMATB/assets/138504487/ae7a8571-2512-4ee3-b5b2-1a2c8978764a)
The joystick I'm using is trustmaster, which runs without problems on v1.1 of the MATB software.

**Comment by benoitvalery** [comment]
The last commit solves this issue. See the version 1.3.0 in [releases](https://github.com/juliencegarra/OpenMATB/releases),
