### ISSUE TITLE
Cannot change audio language

### ISSUE THREAD

**Issue by arthur-perron** [juliencegarra/OpenMATB#32]
Hey there,

I'm trying to change the spoken language right now to English. I have changed the scenario to say:

0:00:00;communications;voicegender;male
0:00:00;communications;voiceidiom;english

and I have made sure that the config matches that scenario. I have also changed the default audio settings set in parameters and still no luck. Is there something I am missing? Please let me know!

Thanks in advance.

**Comment by benoitvalery** [comment]
Hi @arthur-perron,
To change the `communications` language, one must change two variables, that you mentioned: `voicegender` and `voiceidiom`. In fact there was a bug that prevented this to work. Check the last commit and tell me if it is gone!

**Comment by Dannapnt1** [comment]
Hi, not sure if this bug was fixed. We are experiencing the same bug with the latest version 1.30. We are changing both of these parameters voicegender and voiceidion within out scenerio file but the output is still in french.
