### ISSUE TITLE
Question about available keys for RESMAN

### ISSUE THREAD

**Issue by mattonna** [juliencegarra/OpenMATB#38]
Hi ! I was wondering if it would be possible to configure the RESMAN parameters in order to point to other keys thant the numeric pad ?

Indeed, I'm confronted to a laptop that has no numeric keypad.

I tried to define 0:00:00;resman;pump-1-key;1

But I got an error.

Any other suggestion ?

Thanks,

**Comment by juliencegarra** [comment]
Hi, could you provide a minimal scenario producing the error? Thanks

**Comment by mattonna** [comment]
Hi, here is a minimal scenario : 

0:00:00;resman;displayautomationstate;False
0:00:00;resman;pump-1-key;1
0:00:00;resman;tolerancecoloroutside;(241, 100, 100, 255)
0:00:00;resman;start
0:01:00;resman;stop

This leads to this error : 
"Erreur à la ligne 2. pump-1-key devrait être une touche de clavier acceptable (et non 1). Voir la documentation."

**Comment by juliencegarra** [comment]
Could you try using the keys as indicated here:
0:00:00;resman;pump-1-key;_1
or 
0:00:00;resman;pump-1-key;NUM1
(NUM1 for the 1 on the number pad)

The wiki (https://github.com/juliencegarra/OpenMATB/wiki) states to look there for the keys: https://pyglet.readthedocs.io/en/latest/programming_guide/keyboard.html

**Comment by mattonna** [comment]
I tried 0:00:00;resman;pump-1-key;_1 and it worked.
This is what I need, because the laptop I'm using has no number pad.

Thanks !
