### ISSUE TITLE
How can I edit the main for Windows version?

### ISSUE THREAD

**Issue by gferraro2019** [juliencegarra/OpenMATB#8]
Hello,

I'm trying to use OpenMATB for running an experiment with my team at ISAE-SUPAERO but we are going to use a simplified version of it. 

In particular, we are going to use only 4 tasks: sysmon (with 1 square more), track, comm and resman (only 3 tanks).

I edited the plugins and the "placements" in OpenMATB.py for having our desired design and everything works fine in Linux.

Then, I'm using the same modifications for the plugins in Windows but there is not an editable main so how can I edit the placements for the plugins in Win? The goal is to centre the plugins avoiding an empty space only on the right side (because there are 2 tasks fewer).

Thanks in advance.

Regards.

Giuseppe Ferraro

**Comment by benoitvalery** [comment]
Hi Guiseppe,
Glad to hear you was able to use it on Linux.
As for your issue, my opinion is that you should better implement the OpenMATB the same way on both machine : just clone the repository on your Windows machine and install the relevant versions of Python and its libraries - so the `OpenMATB.py` remains editable. (We plan to ameliorates this in the near future, proposing a tiny `main.py`, with a lot of code remaining editable)

If I were you, I would also copy the modified files on the Linux version and paste it into the Windows version (if the idea is to have strictly the same environment on both machine).

The important here is to install the correct versions of Python and its libraries. On thing that can help is the command `pip freeze`. Under Linux, the package is named `python-pip` or `python3-pip`, depending on the version you're using (we tested until Python 3.8, so I recommend you use this version for now).

Once pip is installed, just type `pip freeze` (or `pip3 freeze`) to have a list of the installed python libraries and their version.
For now, the most important are `PySide2`, `pygame`, `rstr`, `psutil` and `wave`.

Hope this helps,
Let me know,

Benoît

**Comment by gferraro2019** [comment]
Hi Benoit,

Thanks for the quick response.

In fact, I've thought about it as well but I was hoping there was an even faster way to do it like an upgrade for the Windows version but as you said this will come in the future.  

Thanks anyway,

Best,

Giuseppe
